/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WritingsRouteImport } from './routes/writings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/songs': typeof SongsRoute
  '/videos': typeof VideosRoute
  '/writings': typeof WritingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/songs': typeof SongsRoute
  '/videos': typeof VideosRoute
  '/writings': typeof WritingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/songs': typeof SongsRoute
  '/videos': typeof VideosRoute
  '/writings': typeof WritingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/journey'
    | '/login'
    | '/photos'
    | '/songs'
    | '/videos'
    | '/writings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/journey'
    | '/login'
    | '/photos'
    | '/songs'
    | '/videos'
    | '/writings'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/journey'
    | '/login'
    | '/photos'
    | '/songs'
    | '/videos'
    | '/writings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  PhotosRoute: typeof PhotosRoute
  SongsRoute: typeof SongsRoute
  VideosRoute: typeof VideosRoute
  WritingsRoute: typeof WritingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  PhotosRoute: PhotosRoute,
  SongsRoute: SongsRoute,
  VideosRoute: VideosRoute,
  WritingsRoute: WritingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
